version: '2'
services:
    gateway:
        image: muraraallan/gateway:latest
        depends_on:
            - mongo
        links:
            - mongo
        environment:
            NODE_ENV: development
            MONGO_URL: mongodb://mongo/DemoApp
        ports:
            - "8000:80"
        entrypoint: "node server"

    mongo:
        image: mongo
