version: "3"
services:
    gateway:
        image: muraraallan/gateway:latest
        depends_on:
            - mongo
        links:
            - mongo
        environment:
            NODE_ENV: Production
            MONGO_URL: mongodb://mongo/DemoApp
        entrypoint: "node server"
    mongo:
        image: mongo
